-- INFO: Hotkey para salvar no modo insert 
function save_file_in_insert_mode()
    vim.cmd([[write]])
    vim.cmd([[startinsert]])
end
vim.api.nvim_set_keymap('i', '<C-S>', '<cmd>lua save_file_in_insert_mode()<CR>', { noremap = true })
-- INFO: Hotkey para criar uma nova aba
vim.api.nvim_set_keymap('i', '<C-n>', '<ESC>:tabnew ', {noremap = true, silent = true})
-- INFO: Hotkeys para mudar entre abas
vim.api.nvim_set_keymap('n', '<C-Right>', ':tabnext<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-Left>', ':tabprevious<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<C-Right>', '<Esc>:tabnext<CR>a', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<C-Left>', '<Esc>:tabprevious<CR>a', {noremap = true, silent = true})
vim.api.nvim_set_keymap('v', '<C-Right>', '<Esc>:tabnext<CR>gv', {noremap = true, silent = true})
vim.api.nvim_set_keymap('v', '<C-Left>', '<Esc>:tabprevious<CR>gv', {noremap = true, silent = true})
vim.api.nvim_set_keymap('c', '<C-Right>', '<C-C>:tabnext<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('c', '<C-Left>', '<C-C>:tabprevious<CR>', {noremap = true, silent = true})
-- INFO: Mapeamento para selecionar texto no modo de inserção
vim.api.nvim_set_keymap('i', '<S-Left>', '<C-o>v', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<S-Right>', '<C-o>ve', { noremap = true, silent = true })
-- INFO: Mapeia a tecla Tab para inserir 3 espaços
vim.api.nvim_set_keymap('i', '<Tab>', '    ', { noremap = true, silent = true })
-- INFO: Duplicate current line above in insert mode
vim.api.nvim_set_keymap('i', '<C-d>', '<Esc>yyP`^a', { noremap = true, silent = true })
-- INFO: Mapeamento para copiar (ctrl+c)
vim.api.nvim_set_keymap('n', '<C-c>', '"+y', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-c>', '"+y', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-c>', '<ESC>"+y', { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<C-c>', '<C-c>"+y', { noremap = true, silent = true })
-- INFO: Mapeamento para colar (ctrl+v)
vim.api.nvim_set_keymap('n', '<C-v>', '"+p', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-v>', '"+p', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-v>', '<ESC>"+pa', { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<C-v>', '<C-c>"+p', { noremap = true, silent = true })
-- INFO: Mapeamento para recortar (ctrl+x)
vim.api.nvim_set_keymap('n', '<C-x>', '"+x', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-x>', '"+x', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-x>', '<ESC>"+x', { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<C-x>', '<C-c>"+x', { noremap = true, silent = true })
-- INFO: Mapeamento para undo (ctrl+z)
vim.api.nvim_set_keymap('', '<C-z>', '<cmd>undo<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-z>', '<cmd>undo<CR>', { noremap = true, silent = true })
-- Mapeamento para redo (ctrl+r)
vim.api.nvim_set_keymap('', '<C-r>', '<cmd>redo<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-r>', '<cmd>redo<CR>', { noremap = true, silent = true })
-- INFO: Mapeamento para salvar (ctrl+s)
vim.api.nvim_set_keymap('n', '<C-s>', '<cmd>write<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-s>', '<cmd>write<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-s>', '<cmd>write<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<C-s>', '<cmd>write<CR>', { noremap = true, silent = true })
-- INFO: Mapeamento para sair (ctrl+q)
vim.api.nvim_set_keymap('n', '<C-q>', '<cmd>quit<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<C-q>', '<cmd>quit<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-q>', '<cmd>quit<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<C-q>', '<cmd>quit<CR>', { noremap = true, silent = true })
